=== qcksys/poe-idol-planner/app/data/schemas/unique-idol.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"name": {
			"type": "object",
			"propertyNames": {
				"type": "string",
				"enum": [
					"en",
					"zh-TW",
					"zh-CN",
					"ko",
					"ja",
					"ru",
					"pt-BR",
					"de",
					"fr",
					"es"
				]
			},
			"additionalProperties": {
				"type": "string"
			},
			"required": [
				"en",
				"zh-TW",
				"zh-CN",
				"ko",
				"ja",
				"ru",
				"pt-BR",
				"de",
				"fr",
				"es"
			]
		},
		"baseType": {
			"type": "string",
			"enum": [
				"Minor",
				"Kamasan",
				"Totemic",
				"Noble",
				"Burial",
				"Conqueror"
			]
		},
		"modifiers": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"text": {
						"type": "object",
						"propertyNames": {
							"type": "string",
							"enum": [
								"en",
								"zh-TW",
								"zh-CN",
								"ko",
								"ja",
								"ru",
								"pt-BR",
								"de",
								"fr",
								"es"
							]
						},
						"additionalProperties": {
							"type": "string"
						},
						"required": [
							"en",
							"zh-TW",
							"zh-CN",
							"ko",
							"ja",
							"ru",
							"pt-BR",
							"de",
							"fr",
							"es"
						]
					},
					"values": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"min": {
									"type": "number"
								},
								"max": {
									"type": "number"
								}
							},
							"required": ["min", "max"],
							"additionalProperties": false
						}
					}
				},
				"required": ["text", "values"],
				"additionalProperties": false
			}
		},
		"flavourText": {
			"type": "object",
			"propertyNames": {
				"type": "string",
				"enum": [
					"en",
					"zh-TW",
					"zh-CN",
					"ko",
					"ja",
					"ru",
					"pt-BR",
					"de",
					"fr",
					"es"
				]
			},
			"additionalProperties": {
				"type": "string"
			},
			"required": [
				"en",
				"zh-TW",
				"zh-CN",
				"ko",
				"ja",
				"ru",
				"pt-BR",
				"de",
				"fr",
				"es"
			]
		}
	},
	"required": ["id", "name", "baseType", "modifiers"],
	"additionalProperties": false
}

=== qcksys/poe-idol-planner/app/data/unique-idols.json
[
	{
		"id": "Eye_of_the_Djinn",
		"name": {
			"en": "Eye of the Djinn",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Scarabs have 50% increased Effect on your Maps per empty Map Device slot",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			}
		]
	},
	{
		"id": "Lone_Adventurer",
		"name": {
			"en": "Lone Adventurer",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "10% increased Pack Size in your Maps",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Only 1 Portal is opened to each of your Maps",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			}
		]
	},
	{
		"id": "Twist_of_Fate",
		"name": {
			"en": "Twist of Fate",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Your Corrupted Rare Maps and any Map Crafting options applying to them are modified unpredictably when opened",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Maps modified in this way have 1-3 additional random Map Modifiers",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			}
		]
	},
	{
		"id": "Wellspring_of_Creation",
		"name": {
			"en": "Wellspring of Creation",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Monsters in your Maps deal (25—30)% less Damage",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 25,
						"max": 30
					}
				]
			},
			{
				"text": {
					"en": "Monsters in your Maps have (40—50)% more Life",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 40,
						"max": 50
					}
				]
			}
		]
	},
	{
		"id": "Dance_of_Destruction",
		"name": {
			"en": "Dance of Destruction",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Monsters in your Maps deal (20—25)% more Damage",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 20,
						"max": 25
					}
				]
			},
			{
				"text": {
					"en": "Monsters in your Maps have (25—30)% less Life",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 25,
						"max": 30
					}
				]
			}
		]
	},
	{
		"id": "Singular_Focus",
		"name": {
			"en": "Singular Focus",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Maps found have (200—220)% more chance to be Favoured Maps",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 200,
						"max": 220
					}
				]
			},
			{
				"text": {
					"en": "Non-Favoured Maps found in your Maps drop as Basic Currency Items instead",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			}
		]
	},
	{
		"id": "Eldritch_Gaze",
		"name": {
			"en": "Eldritch Gaze",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Eldritch Altars Influenced by The Eater of Worlds have an additional Downside",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Eldritch Altars Influenced by The Eater of Worlds have (50—60)% increased Effect of Upsides",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 50,
						"max": 60
					}
				]
			}
		]
	},
	{
		"id": "Wrath_of_the_Cosmos",
		"name": {
			"en": "Wrath of the Cosmos",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Eldritch Altars Influenced by The Searing Exarch have (50—60)% chance to have an additional Upside",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 50,
						"max": 60
					}
				]
			},
			{
				"text": {
					"en": "Eldritch Altars Influenced by The Searing Exarch which have an additional Upside have (80—100)% increased Effect of Downsides",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": [
					{
						"min": 80,
						"max": 100
					}
				]
			}
		]
	},
	{
		"id": "Shadow_Shaping",
		"name": {
			"en": "Shadow Shaping",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Maps found cannot be your Favoured Maps",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			},
			{
				"text": {
					"en": "Maps found in your Maps have +1% chance to have a special Implicit Modifier for each different Map you have Favoured",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
			}
		]
	},
	{
		"id": "Extreme_Archaeology",
		"name": {
			"en": "Extreme Archaeology",
			"zh-TW": "",
			"zh-CN": "",
			"ko": "",
			"ja": "",
			"ru": "",
			"pt-BR": "",
			"de": "",
			"fr": "",
			"es": ""
		},
		"baseType": "Minor",
		"modifiers": [
			{
				"text": {
					"en": "2% increased Maps found in Area",
					"zh-TW": "",
					"zh-CN": "",
					"ko": "",
					"ja": "",
					"ru": "",
					"pt-BR": "",
					"de": "",
					"fr": "",
					"es": ""
				},
				"values": []
